version: 'latest'

services:
  next-app:
    container_name: next-app-dev
    build:
      dockerfile: .dockerfile
      args:
        ENV_PRISMA_URL: ${ENV_PRISMA_URL}
        NEXT_PUBLIC_ENV_API: ${NEXT_PUBLIC_ENV_API}
    restart: always
    ports:
      - 3000:3000
    networks:
      - db
  db:
    container_name: postgres-dev
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      POSTGRES_DB: db
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  db:
    driver: bridge

volumes:
  db:
    driver: local
