import Provider from '@/hooks/sessionProvider';
import '../../(routes)/globals.css'
import { getServerSession } from "next-auth";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <Provider session={session}>
        <body>{children}</body>
      </Provider>

    </html>
  )
}
