import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { Modal } from "@/components/modal/modal";
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import { Button } from "@/components/ui/button";
import { Settings } from 'lucide-react';
import Link from "next/link";
import ReactQueryProvider from "./ReactQueryProvider";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body className={cn(
          "min-h-screen  bg-background font-sans antialiased",
          fontSans.variable
        )}>
          <nav className='w-full justify-between flex bg-green-900 rounded  items-center pt-1 pb-1 pr-1 pl-1'>
            <div>
              <Link href={'/'} className="hover:bg-opacity-30 hover:rounded-2xl text-white hover:text-white">
                <Button variant='ghost' className="hover:bg-opacity-80  text-white hover:text-black">Inicio</Button>
              </Link>
              <Link href={'/batchs'} >
                <Button variant='ghost' className="hover:bg-opacity-100  text-white hover:text-black">Cortes</Button>
              </Link>
              <Link href={'/sections'} >
                <Button variant='ghost' className="hover:bg-opacity-100  text-white hover:text-black">Secções</Button>
              </Link>
            </div>
            <Link href={`/settings`}>
              <Button size='icon' variant='ghost' className="hover:bg-black  hover:bg-opacity-30 hover:rounded-2xl text-white hover:text-white">
                <Settings className="h-6 w-6" />
              </Button>
            </Link>
          </nav>
          {children}
          <Modal />
          <Toaster />
        </body>
      </ReactQueryProvider>
    </html>
  );
}
