import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { Modal } from "@/components/modal/modal";
import { Toaster } from "@/components/ui/toaster"
import { cn } from "@/lib/utils"
import ReactQueryProvider from "./ReactQueryProvider";
import Provider from "@/hooks/sessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { NavBar } from "@/components/navBar/NavBar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions)
  return (
    <html lang="en">
      <Provider session={session}>
        <ReactQueryProvider>
          <body className={cn(
            "min-h-screen  bg-background font-sans antialiased",
            fontSans.variable
          )}>
            <NavBar />
            {children}
            <Modal />
            <Toaster />
          </body>
        </ReactQueryProvider>
      </Provider>
    </html>
  );
}
