import type { Metadata } from "next";
import "./globals.css";
import { Modal } from "@/components/modal/modal";
import { Toaster } from "@/components/ui/toaster"
import ReactQueryProvider from "./ReactQueryProvider";
import { NavBar } from "@/components/nagivation/navBar/NavBar";
import { RequireAuth } from "@/components/Layout/RequireAuth";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <RequireAuth>
      <ReactQueryProvider>
        <div>
          <NavBar />
          <div className="flex-grow">
            <div className="flex w-full flex-col items-center p-10 mx-auto">
              {children}
            </div>
          </div>
          <Modal />
          <Toaster />
        </div>
      </ReactQueryProvider>
    </RequireAuth>

  );
}
